### ISSUE TITLE
Unhandled rejection WarehouseError

### ISSUE THREAD

**Issue by andyzys** [jaredly/hexo-admin#102]
There is a error when I finish my editing and click the publish button to publish.  It has already successfully publish the paper to website. Is this a hexo's issue or hexo-admin's issue?

here is err log:

```
Unhandled rejection WarehouseError: ID `source/_drafts/js-anthology.md` has been used
    at new WarehouseError (hexo\andyzou\node_modules\warehouse\lib\error.js:17:11)
    at Model._insertOne (hexo\andyzou\node_modules\warehouse\lib\model.js:185:27)
    at  hexo\andyzou\node_modules\warehouse\lib\model.js:214:17
    at tryCatcher (hexo\andyzou\node_modules\bluebird\js\release\util.js:16:23)
    at hexo\andyzou\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (hexo\andyzou\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (hexo\andyzou\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (hexo\andyzou\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (hexo\andyzou\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (hexo\andyzou\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (hexo\andyzou\node_modules\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (hexo\andyzou\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (hexo\andyzou\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (hexo\andyzou\node_modules\bluebird\js\release\promise.js:572:26)
    at Promise._settlePromise0 (hexo\andyzou\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (hexo\andyzou\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (hexo\andyzou\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (hexo\andyzou\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (hexo\andyzou\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by PirtleShell** [comment]
What version of hexo are you using? What does the front matter of `js-anthology.md` look like?

Are you able to create a new post in the terminal? `hexo new post`
Also, can you reproduce this in a fresh hexo instance?

[`warehouse`](https://github.com/tommy351/warehouse) is the database structure used by hexo.

Definitely related to https://github.com/jaredly/hexo-admin/issues/65.

**Comment by andyzys** [comment]
Thanks for your answer.
It seems like there's issue of front-matter format, I modified it, It will be ok.
