### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#126]
```
$ gulp
[14:49:42] Using gulpfile E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\gulpfile.js
[14:49:42] Starting 'less'...
[14:49:42] Starting 'javascript'...
[14:49:42] Starting 'watch'...
[14:49:42] Finished 'watch' after 58 ms
[14:49:42] Finished 'less' after 216 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

ReactifyError: E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\client\post.js: Parse Error: Line 122: Unexpected token ; while parsing file: E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\client\post.js
    at throwError (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:2338:21)
    at throwUnexpected (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:2400:9)
    at expect (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:2409:13)
    at parseArguments (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:2930:17)
    at parseLeftHandSideExpressionAllowCall (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:2994:24)
    at parsePostfixExpression (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:3030:20)
    at parseUnaryExpression (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:3060:20)
    at parseBinaryExpression (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:3187:16)
    at parseConditionalExpression (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:3247:16)
    at parseAssignmentExpression (E:\WorkSpace\webProject\Hexo-development\hexo-admin_220\node_modules\hexo-admin\node_modules\reactify\node_modules\esprima-fb\esprima.js:3457:16)

```

**Comment by PirtleShell** [comment]
I also get a build error. Looking into it.

**Comment by PirtleShell** [comment]
There was an extra curly bracket going on in `post.handleRemove`. Should be resolved now!
