### ISSUE TITLE
Plugin load failed 

### ISSUE THREAD

**Issue by Heshichun** [jaredly/hexo-admin#128]
OS X 10.11 
Hexo 3.2.2

when I started `hero -s` 

report

`ERROR Plugin load failed: hexo-admin
Error: [Hexo Admin]: the provided password_hash looks like an md5 hash -- hexo-admin has switched to use bcrypt; see the Readme for more info.
    at /Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo-admin/index.js:14:11
    at /Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Anhedonia/Desktop/hexo_for_Jiaqi/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)`

**Comment by PirtleShell** [comment]
Did you generate the admin section of your config with hexo-admin's authentification setup?

Also, is your hosting dynamic? You can't use hexo-admin on static-serving-only servers, see #43 & #90.

**Comment by Heshichun** [comment]
but I even can't use it on localhost

**Comment by tunacon** [comment]
May be wrong password_hash ??

**Comment by PirtleShell** [comment]
were you able to resolve this problem?

**Comment by ysf-1999** [comment]
I had the same problem. please help me.
