### ISSUE TITLE
Error: spawn ./hexo-deploy.bat ENOENT

### ISSUE THREAD

**Issue by LiuKaixin** [jaredly/hexo-admin#149]
when I try to click the "deploy" button, it returns such message:
res { Error: spawn ./hexo-deploy.bat ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ./hexo-deploy.bat',
  path: './hexo-deploy.bat',
  spawnargs: [ '' ] } { stdout: '', stderr: '' }

but I did not modify anything....
Help me, Please!

**Comment by pirtleshell** [comment]
Hi @LiuKaixin, sorry for the delay. The child process is unable to find that file. Try using the full path to the file (ie. `deployCommand: /path/to/project/hexo-deploy.bat`). Let me know if that works for you.
