### ISSUE TITLE
ERROR Plugin load failed: hexo-admin SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by lucifer7** [jaredly/hexo-admin#154]
When start hexo after install and configure hexo-admin, error reported:
```
/root/blog/node_modules/hexo-admin/api.js:103
      hexo.log.d(`renamed ${model.toLowerCase()} to ${body.filename}`)
                 ^
ERROR Plugin load failed: hexo-admin
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/root/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /root/blog/node_modules/hexo-admin/index.js:4:9
    at /root/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /root/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /root/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:272:14
    at /root/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /root/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /root/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:108:15)

```

Version info:
```
localhost blog (hexo*) # npm list hexo-admin         
hexo-site@0.0.0 /root/blog
└── hexo-admin@2.2.

localhost blog (hexo*) # hexo -version
hexo: 3.3.6
hexo-cli: 1.0.2
os: Linux 2.6.32-431.el6.x86_64 linux x64
http_parser: 1.2
node: 0.10.48
v8: 3.14.5.11
ares: 1.9.0-DEV
uv: 0.10.34
zlib: 1.2.3
modules: 11
openssl: 1.0.1e-fips
```

**Comment by lucifer7** [comment]
hexo-admin@2.1.0 is ok, only 2.2.x reports this error. But seems that 2.1.0 have no Settings page?

**Comment by lucifer7** [comment]
Problem fixed when update both npm and node to newer version. Now version 2.2.x is fine, and Settings page is showing now.

```
root:blog/ (hexo✗) # npm version                                                                       [13:15:07]
{ 'hexo-site': '0.0.0',
  npm: '5.5.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.1',
  openssl: '1.0.2m',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.47',
  zlib: '1.2.11' }

```

**Comment by rudy2steiner** [comment]
i meet the same situation and just downgrade to version 2.1.0
