### ISSUE TITLE
Error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by duqian42707** [jaredly/hexo-admin#169]
I'm using hexo and hexo-admin in a docker image.
My docker image is `FROM node:alpine`.
The `Dockerfile` looks like:
```
FROM node:alpine

ADD . /app
WORKDIR /app

RUN npm config set registry https://registry.npm.taobao.org
RUN npm install hexo-cli -g
RUN npm install

EXPOSE 4000
CMD ["hexo", "s"]
``` 

The `_config.yml` file looks like:
```yml
admin:
    username: xxxx
    password_hash: xxxx
    secret: my super secret phrase
    deployCommand: './deploy.sh'
```
Then when I post a new post ,  and click the `deploy` button,  the error occurred:
```
(node:1) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
EEE { Error: spawn Unknown system error -8
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:525:9)
    at module.exports (/app/node_modules/hexo-admin/deploy.js:14:14)
    at /app/node_modules/hexo-admin/api.js:413:7
    at /app/node_modules/hexo-admin/api.js:141:7
    at call (/app/node_modules/connect/index.js:239:7)
    at next (/app/node_modules/connect/index.js:183:5)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at next (/app/node_modules/connect/index.js:161:14)
    at /app/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
  errno: 'Unknown system error -8',
  code: 'Unknown system error -8',
  syscall: 'spawn' }

```

**Comment by pirtleshell** [comment]
hi there, 

the spawn error is probably caused by your deploy command.

have you written a `deploy.sh` script and confirmed it contains no errors? if yes, try to set the `deployCommand` to an absolute instead of relative path (ie. `./deploy.sh` -> `/path/to/deploy.sh`). also make sure that it has executable permission.

let us know if that fixes your problem.

**Comment by duqian42707** [comment]
hi,
The error still exists even I use an absolute path `/app/deploy.sh`

The deploy command is ok. It is at `/app/deploy.sh` . And there is only a line in the `deploy.sh` file.
```shell
echo 'ok'
```
When I enter the docker container with `docker exec -it <container> /bin/sh` ,
and run the deploy command . It works well.
```shell
/app # ./deploy.sh 
ok
/app # /app/deploy.sh
ok
/app # 
```

**Comment by pirtleshell** [comment]
interesting. what operating system are you running on?

i'm not sure what's up with error code -8, but positive 8 on windows is `NOT_ENOUGH_MEMORY`. i suspect that's not the actual problem given you're only trying to echo "ok".

does deploy.sh have the executable permission? and can you try adding the following shebang as the first line of the file (it might not know what binary to run your file with?):
`#!/bin/sh`

**Comment by duqian42707** [comment]
I'm using docker, and the base image was `node:alpine`.

I fixed the problem by changing the base image from `node:alpine` to `centos:7`.

Now the `Dockerfile` look like:

```
FROM centos:7

ADD . /app
WORKDIR /app

RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash - \
    && yum install -y git openssh nodejs

RUN npm config set registry https://registry.npm.taobao.org
RUN npm install hexo-cli -g
RUN npm install

EXPOSE 4000

CMD ["hexo", "s"]
```
