### ISSUE TITLE
When I  click 'deploy' botton, show 'EEE TypeError: Cannot read property 'on' of undefined'

### ISSUE THREAD

**Issue by songxingguo** [jaredly/hexo-admin#179]
error:
`EEE TypeError: Cannot read property 'on' of undefined
    at module.exports (/root/blog/node_modules/hexo-admin/deploy.js:17:15)
    at /root/blog/node_modules/hexo-admin/api.js:413:7
    at /root/blog/node_modules/hexo-admin/api.js:141:7
    at call (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:2                                                                                                             39:7)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             83:5)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at next (/root/blog/node_modules/hexo-server/node_modules/connect/index.js:1                                                                                                             61:14)
    at /root/blog/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/root/blog/node_modules/raw-body/index.js:224:16)
    at done (/root/blog/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/root/blog/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./hexo-deploy.sh EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[root@izuf6fczkfsauetjjufgstz blog]# hexo s
(node:16277) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
`

**Comment by songxingguo** [comment]
Ｉhave solved this problem . Because there is no authorization， after i do  `
chmod +x hexo-deploy.sh`  ,it's work.  For details, please see [hexo 通过hexo-admin进行全自动发布文章](https://blog.csdn.net/dataiyangu/article/details/83066586).
