### ISSUE TITLE
ERROR Plugin load failed: hexo-admin

### ISSUE THREAD

**Issue by bluesky4485** [jaredly/hexo-admin#19]
OS version:win8.1 x64
node  version:0.12.0

    npm install hexo-cli -g
    hexo init blog
    cd blog
    npm install
    hexo server

this works fine.
but when *npm install --save hexo-admin-plugin*, then *hexo server*,I get the error :
ERROR Plugin load failed: hexo-admin
ReferenceError: hexo is not defined

why I got this error?

I install *hexo-generator-feed* plugin with the same error.

**Comment by jaredly** [comment]
What version of hexo is it? They may have changed things.

**Comment by bluesky4485** [comment]
@jaredly 
hexo version: 3.0.0-rc.4

**Comment by jaredly** [comment]
Ah yes, I haven't updated this plugin for the new hexo release yet, sorry.
My own blog is still on the 2.x release.

**Comment by mzalazar** [comment]
this does NOT working with version 3.0.0 :(

**Comment by xiuweikang** [comment]
this plugin is very useful, could you update it to adapt hexo 3.x?

**Comment by huangjihua** [comment]
ReferenceError: hexo is not defined
    at Object.<anonymous> (L:\Workspaces\WebStormProject\hexo\node_modules\hexo-admin-plugin\update.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (L:\Workspaces\WebStormProject\hexo\node_modules\hexo-admin-plugin\api.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\lib\hexo\index.js:213:21)
    at L:\Workspaces\WebStormProject\hexo\node_modules\hexo-admin-plugin\index.js:7:11
    at L:\Workspaces\WebStormProject\hexo\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (L:\Workspaces\WebStormProject\hexo\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:415:13)

**Comment by jaredly** [comment]
@huangjihua what Hexo version, and what Hexo-admin version?

**Comment by jaredly** [comment]
Hexo-admin now works on Hexo version 3.x
