### ISSUE TITLE
hexo-admin deploy 出现Error: spawn UNKNOWN 的错误

### ISSUE THREAD

**Issue by binbin1808** [jaredly/hexo-admin#194]
EEE { Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at module.exports (C:\Users\彬彬\Desktop\blog\node_modules\hexo-admin\deploy.js:14:14)
    at C:\Users\彬彬\Desktop\blog\node_modules\hexo-admin\api.js:413:7
    at C:\Users\彬彬\Desktop\blog\node_modules\hexo-admin\api.js:141:7
    at call (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:239:7)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:183:5)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at next (C:\Users\彬彬\Desktop\blog\node_modules\connect\index.js:161:14)
    at C:\Users\彬彬\Desktop\blog\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (C:\Users\彬彬\Desktop\blog\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\彬彬\Desktop\blog\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\彬彬\Desktop\blog\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:194:15) errno: 'UNKNOWN', code: 'UNKNOWN', syscall: 'spawn' }

**Comment by binbin1808** [comment]
求大佬给个解决方案呀

**Comment by winterZhao** [comment]
直接改的代码，他代码里用的nodejs的spawn，找到这里(C:\Users\彬彬\Desktop\blog\node_modules\hexo-admin\deploy.js:14，改一下源码，我是这么做的

**Comment by binbin1808** [comment]
嗯嗯我去试试看
