### ISSUE TITLE
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default. 

### ISSUE THREAD

**Issue by miozus** [jaredly/hexo-admin#222]
hexo server --debug
```bash
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/Users/username/hexo/blog/node_modules/_js-yaml@4.1.0@js-yaml/index.js:10:11)
    **at getSettings (/Users/username/hexo/blog/node_modules/_hexo-admin@2.3.0@hexo-admin/api.js:44:26)**
    at /Users/username/hexo/blog/node_modules/_hexo-admin@2.3.0@hexo-admin/api.js:150:14
    at /Users/username/hexo/blog/node_modules/_hexo-admin@2.3.0@hexo-admin/api.js:141:7
    at call (/Users/username/hexo/blog/node_modules/_connect@3.7.0@connect/index.js:239:7)
    at next (/Users/username/hexo/blog/node_modules/_connect@3.7.0@connect/index.js:183:5)
    at next (/Users/username/hexo/blog/node_modules/_connect@3.7.0@connect/index.js:161:14)
    at jsonParser (/Users/username/hexo/blog/node_modules/_body-parser@1.19.0@body-parser/lib/types/json.js:110:7)
    at call (/Users/username/hexo/blog/node_modules/_connect@3.7.0@connect/index.js:239:7)
    at next (/Users/username/hexo/blog/node_modules/_connect@3.7.0@connect/index.js:183:5)
    at SendStream.error (/Users/username/hexo/blog/node_modules/_serve-static@1.14.1@serve-static/index.js:121:7)
    at SendStream.emit (events.js:376:20)
    at SendStream.error (/Users/username/hexo/blog/node_modules/_send@0.17.1@send/index.js:270:17)
    at SendStream.onStatError (/Users/username/hexo/blog/node_modules/_send@0.17.1@send/index.js:421:12)
    at next (/Users/username/hexo/blog/node_modules/_send@0.17.1@send/index.js:735:16)
    at onstat (/Users/username/hexo/blog/node_modules/_send@0.17.1@send/index.js:724:14)
    at FSReqCallback.oncomplete (fs.js:192:21)
```

package.json
```json
 "dependencies": {
    "hexo": "^5.0.0",
    "hexo-admin": "^2.3.0",
...
```

**Comment by miozus** [comment]
```javascript
		// reads admin panel settings from _admin-config.yml
    // or writes it if it does not exist
    function getSettings() {
        var path = hexo.base_dir + '_admin-config.yml'
        if (!fs.existsSync(path)) {
            hexo.log.d('admin config not found, creating one')
            fs.writeFile(hexo.base_dir + '_admin-config.yml', '')
            return {}
        } else {
            var settings = yml.load(fs.readFileSync(path))
//                              ⬆️  safeLoad -> load
														
            if (!settings) return {}
            return settings
        }
```

其实呢，hexo 版本升级后语法(js-yaml)要求更严格，直接定位，修改老版本的源码就能运行啦

考虑有的同学还在用老版本，我也不知怎么获取版本做兼容，所以没提PR

**Comment by jerryoung** [comment]
版本兼容，我已经实现会，谢谢楼主。
