### ISSUE TITLE
Plugin can't load properly

### ISSUE THREAD

**Issue by maruwtc** [jaredly/hexo-admin#228]
12:12:11 AM: ERROR {
12:12:11 AM:   err: Error: [Hexo Admin]: the provided password_hash looks like an md5 hash -- hexo-admin has switched to use bcrypt; see the Readme for more info.
12:12:11 AM:       at /opt/build/repo/node_modules/hexo-admin/index.js:14:11
12:12:11 AM:       at /opt/build/repo/node_modules/hexo/lib/hexo/index.js:298:14
12:12:11 AM:       at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
12:12:11 AM:       at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
12:12:11 AM:       at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
12:12:11 AM:       at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
12:12:11 AM:       at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
12:12:11 AM:       at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12)
12:12:11 AM:       at _drainQueue (/opt/build/repo/node_modules/bluebird/js/release/async.js:86:9)
12:12:11 AM:       at Async._drainQueues (/opt/build/repo/node_modules/bluebird/js/release/async.js:102:5)
12:12:11 AM:       at Immediate.Async.drainQueues [as _onImmediate] (/opt/build/repo/node_modules/bluebird/js/release/async.js:15:14)
12:12:11 AM:       at processImmediate (node:internal/timers:466:21)
12:12:11 AM: } Plugin load failed: %s hexo-admin

**Comment by wangyunzi** [comment]
I had the same problem as you！
