### ISSUE TITLE
ERROR Plugin load failed: hexo-admin ReferenceError: hexo is not defined

### ISSUE THREAD

**Issue by iqiancheng** [jaredly/hexo-admin#23]
Err:

```
ERROR Plugin load failed: hexo-admin
ReferenceError: hexo is not defined
    at Object.<anonymous> (h:\QianCheng\qiancheng.me\node_modules\hexo-admin\update.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (h:\QianCheng\qiancheng.me\node_modules\hexo-admin\api.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (h:\QianCheng\qiancheng.me\node_modules\hexo\lib\hexo\index.js:213:21)
    at h:\QianCheng\qiancheng.me\node_modules\hexo-admin\index.js:7:11
    at h:\QianCheng\qiancheng.me\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\async.js:175:16)
    at Async._drainQueues (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\async.js:185:10)
    at Async.drainQueues (h:\QianCheng\qiancheng.me\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:415:13)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

Env:
```
hexo: 3.0.1
os: Windows_NT 6.2.9200 win32 ia32
http_parser: 1.0
node: 0.10.22
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.19
zlib: 1.2.3
modules: 11
openssl: 1.0.1e
```

**Comment by semos** [comment]
Hi @iqiancheng 
This issue has already been reported: #19

Downgrade to Hexo 2.x or check out this pull request #20

**Comment by iqiancheng** [comment]
thx.
