### ISSUE TITLE
Can't create new post on windows

### ISSUE THREAD

**Issue by jiji262** [jaredly/hexo-admin#47]
* Issue One: new post submission button has no response.
![issue 1](https://cdn.pbrd.co/images/pLmjWoZ.gif)

* Issue Two: use enter to create new post, a error occurs:
![issue2](https://cdn.pbrd.co/images/pLpKI2o.gif)

```java
D:\hexo\blog  (hexo-site@0.0.0)
λ chexo server -d
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: Cannot read property 'source' of undefined
    at addIsDraft (D:\hexo\blog\node_modules\hexo-admin\api.js:10:24)
    at D:\hexo\blog\node_modules\hexo-admin\api.js:186:18
    at tryCatcher (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\release\util.js
:11:23)
    at Promise._settlePromiseFromHandler (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\blue
bird\js\release\promise.js:489:31)
    at Promise._settlePromise (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\rel
ease\promise.js:546:18)
    at Promise._settlePromise0 (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\re
lease\promise.js:591:10)
    at Promise._settlePromises (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\re
lease\promise.js:674:18)
    at Async._drainQueue (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\release\
async.js:125:16)
    at Async._drainQueues (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\bluebird\js\release
\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\blog\node_modules\hexo\node_modules\hexo-fs\node_
modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by edravis** [comment]
+1

**Comment by dbYoung** [comment]
not enough dependency installed.

try `npm install` then open http://0.0.0.0:4000/

You'll see hexo front page. and your admin page works likes charm

**Comment by jaredly** [comment]
I just fixed issue 1 -- @jiji262 could you give me more information about issue 2? What version of hexo are your running?

**Comment by jiji262** [comment]
@jaredly the latest version of hexo

**Comment by jaredly** [comment]
hmm and it looks like you're on windows? that's likely the difference.
it seems that [this line](https://github.com/jaredly/hexo-admin/blob/master/api.js#L186) is failing to find the right post, which likely means that the slashes are going the wrong direction in the `source` variable.
Could you add a logging statement to see the value of `source` at that line? Then we'd know (probably) how to fix this

**Comment by dalibormesaric** [comment]
source is `_drafts\Untitled.md`

**Comment by jaredly** [comment]
@jiji262 can you try again, using HEAD? I just merged in #59, which hopefully will fix your problem

**Comment by dalibormesaric** [comment]
works for me after the update :+1:

**Comment by jaredly** [comment]
great to hear!
