### ISSUE TITLE
not support hexo JSON Front-matter

### ISSUE THREAD

**Issue by jeremyxu2010** [jaredly/hexo-admin#64]
my hexo JSON Front-matter as follows:

```
;;;
"title": "我的VIM配置",
"categories": "工具",
"tags": ["linux", "vim"]
;;;

```

and i select this markdown file to edit, error came out:

```
YAMLException: end of the stream or a document separator is expected at line 1, column 19:
    "title": "我的VIM配置",
                      ^
    at generateError (/Users/jeremy/dev/git/blog/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/jeremy/dev/git/blog/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDocument (/Users/jeremy/dev/git/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1508:5)
    at loadDocuments (/Users/jeremy/dev/git/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/Users/jeremy/dev/git/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at parseYAML (/Users/jeremy/dev/git/blog/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at Function.parse (/Users/jeremy/dev/git/blog/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at module.exports (/Users/jeremy/dev/git/blog/node_modules/hexo-admin/update.js:31:20)
    at /Users/jeremy/dev/git/blog/node_modules/hexo-admin/api.js:221:5
    at /Users/jeremy/dev/git/blog/node_modules/hexo-admin/api.js:91:7
```

**Comment by PirtleShell** [comment]
I can confirm this is still true. The metadata is recognized, but the post content is not inserted into the codemirror editor.

![json frontmatter does not work](https://cloud.githubusercontent.com/assets/14897503/22941906/2d252836-f29c-11e6-8214-c5efe076a188.png)

We should fix this to ensure people can migrate to the admin easily.
