### ISSUE TITLE
cannot publish content, Unhandled rejection TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by hsiunien** [jaredly/hexo-admin#69]
i'm the first time to use admin 
when i edit a article,and modify some text ,then i click publish,
the console show me this text:

`hsiuniendeMBP:blog hsiunien$ hexo server -d
INFO  Start processing
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: Cannot read property 'source' of undefined
    at addIsDraft (/Users/hsiunien/www/blog/node_modules/hexo-admin/api.js:11:24)
    at /Users/hsiunien/www/blog/node_modules/hexo-admin/api.js:51:16
    at /Users/hsiunien/www/blog/node_modules/hexo-admin/update.js:76:9
    at tryCatcher (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._settlePromise (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:572:21)
    at Promise._settlePromise0 (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/map.js:97:18)
    at Promise._settlePromise (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/hsiunien/www/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)`

**Comment by wonderful60** [comment]
I also encountered the same problem.
```
Unhandled rejection TypeError: Cannot read property 'source' of undefined
    at addIsDraft (c:\Users\logtous\hexo-logtous\node_modules\hexo-admin\api.js:11:24)
    at c:\Users\logtous\hexo-logtous\node_modules\hexo-admin\api.js:51:16
    at c:\Users\logtous\hexo-logtous\node_modules\hexo-admin\update.js:76:9
    at tryCatcher (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._settlePromise (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:572:21)
    at Promise._settlePromise0 (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:628:18)
    at MappingPromiseArray.PromiseArray._resolve (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\map.js:97:18)
    at Promise._settlePromise (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:564:26)
    at Promise._settlePromise0 (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\logtous\hexo-logtous\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

INFO  Now start qiniu sync.
INFO  Need upload file num: 0






```

**Comment by grinka** [comment]
Probably it's the same problem as described here : #68

**Comment by PirtleShell** [comment]
closing for inactivity
