### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by eromoe** [jaredly/hexo-admin#72]
I get this error when I try to create a new post.

```
Unhandled rejection TypeError: Cannot read property 'source' of undefined
    at addIsDraft (E:\Project\hexoblog\node_modules\hexo-admin\api.js:11:24)
    at E:\Project\hexoblog\node_modules\hexo-admin\api.js:187:18
    at tryCatcher (E:\Project\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._settlePromise (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:572:21)
    at Promise._settlePromise0 (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:445:14)
    at Promise._settlePromiseFromHandler (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (E:\Project\hexoblog\node_modules\bluebird\js\release\promise.js:628:18)
    at MappingPromiseArray.PromiseArray._resolve (E:\Project\hexoblog\node_modules\bluebird\js\release\promise_array.js:
125:19)
    at MappingPromiseArray._promiseFulfilled (E:\Project\hexoblog\node_modules\bluebird\js\release\map.js:97:18)
    at MappingPromiseArray.PromiseArray._iterate (E:\Project\hexoblog\node_modules\bluebird\js\release\promise_array.js:
113:31)
    at MappingPromiseArray.init (E:\Project\hexoblog\node_modules\bluebird\js\release\promise_array.js:77:10)
```

hexo cli work well:

```
E:\Project\hexoblog>hexo new asdasdasd
INFO  Created: E:\Project\hexoblog\source\_posts\asdasdasd.md
```

Maybe due to cross origin?
chrome console:

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
bundle.js:845 Failed! to make post Error: Origin is not allowed by Access-Control-Allow-Origin(…)
```

**Comment by eromoe** [comment]
seems dup to https://github.com/jaredly/hexo-admin/issues/47, and fixed?
I install this package by npm

**Comment by eromoe** [comment]
```
npm remove hexo-admin
npm install jaredly/hexo-admin
```
open http://localhost:4000/admin/
got `Cannot GET /admin/`

**Comment by AndreiD** [comment]
up. same error...

**Comment by seshaljain** [comment]
@eromoe had the same problem, `npm install hexo-admin` won't do, you have to use `npm install hexo-admin --save`. Notice the `--save` flag, which will list hexo-admin as a dependency in package.json. Hexo plugins work that way. From [Hexo Plugin Docs](https://hexo.io/docs/plugins.html):
> You’ll also need to list your plugin as a dependency in the root package.json of your hexo instance in order for Hexo to detect and load it.
