### ISSUE TITLE
deploy Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by xbotao** [jaredly/hexo-admin#94]
I follow [#70](https://github.com/jaredly/hexo-admin/issues/70) to do.
But there is an error when I click the 'Deploy' button.
Error is 
"Error: spawn UNKNOWN"

-----
I use windows and firefox brower.

**Comment by PirtleShell** [comment]
Does `hexo deploy` function as expected when run from the command line?

**Comment by xbotao** [comment]
The command `hexo deploy` is OK when run from the comamnd line.

**Comment by xbotao** [comment]
Error Info
```Bash
$ hexo s -d
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
EEE { Error: spawn UNKNOWN
    at exports._errnoException (util.js:953:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at module.exports (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\he                            xo-admin\deploy.js:14:14)
    at E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\hexo-admin\api.js:                            265:7
    at E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\hexo-admin\api.js:                            91:7
    at call (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:239:7)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:183:5)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at next (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\connect\inde                            x.js:161:14)
    at E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\body-parser\lib\re                            ad.js:129:5
    at invokeCallback (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\ra                            w-body\index.js:262:16)
    at done (E:\WorkSpace\webProject\Hexo-oschina\blog\node_modules\raw-body\ind                            ex.js:251:7)
    at IncomingMessage.onEnd (E:\WorkSpace\webProject\Hexo-oschina\blog\node_mod                            ules\raw-body\index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7) code: 'UNKNOWN', errno: 'UNKNOWN',                             syscall: 'spawn' }

```

**Comment by PirtleShell** [comment]
Deploy uses [child_process](https://nodejs.org/api/child_process.html) to run your deploy command. It looks like the `UNKNOWN` errors occur either from permissions issues ([this stackoverflow question](https://stackoverflow.com/questions/30809808/node-webkit-child-spawn-unknown-error)) or from how Windows doesn't support shebangs to directly run files (https://github.com/babel/babili/issues/108#issuecomment-242938483).

What is the `admin.deployCommand` of your `_config.yml`? Try running the command directly in the terminal. Does it deploy correctly?

**Comment by xbotao** [comment]
Running the command directly in the terminal is correctly.
![qq 20170102104526](https://cloud.githubusercontent.com/assets/6964173/21584176/9d185b1c-d0d8-11e6-9999-64b0c564bce1.jpg)

```
admin:
  deployCommand: './hexo-deploy.sh'
```

**Comment by PirtleShell** [comment]
I think it's a permissions or shebang problem like from the posts mentioned above. You'll just have to play around with it to get it to work with Windows.

What are the contents of `hexo-deploy.sh`?

Does deploying work when you start hexo with administrative privileges (`sudo hexo server`)?

If that doesn't work, try setting `deployCommand` to the following and see if either of them work:
* `hexo deploy`
* `sh hexo-deploy.sh`

**Comment by xbotao** [comment]
The contents of  `hexo-deploy.sh`
```
#!/usr/bin/env sh
hexo g && hexo d
```

---
```
$ sudo hexo s -d
bash: sudo: command not found
```
---
```
admin:
  deployCommand: 'hexo deploy'
```
error log
```
res { Error: spawn hexo deploy ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn hexo deploy',
  path: 'hexo deploy',
  spawnargs: [ '' ] } { stdout: '', stderr: '' }
```
---
```
admin:
  deployCommand: 'sh hexo-deploy.sh'
```
error log
```
res { Error: spawn sh hexo-deploy.sh ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn sh hexo-deploy.sh',
  path: 'sh hexo-deploy.sh',
  spawnargs: [ '' ] } { stdout: '', stderr: '' }
```
---
```
admin:
  deployCommand: 'node ./node_modules/hexo/bin/hexo deploy'
```
error log
```
res { Error: spawn node ./node_modules/hexo/bin/hexo deploy ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node ./node_modules/hexo/bin/hexo deploy',
  path: 'node ./node_modules/hexo/bin/hexo deploy',
  spawnargs: [ '' ] } { stdout: '', stderr: '' }
```

**Comment by xbotao** [comment]
I found a compromise method to deploy blog by click the deploy button.

create a `hexo-deploy.bat` file 
```
hexo d
```
and set the `deployCommand` to `deployCommand: 'hexo-deploy.bat'`
But a cmd console will pop when click the deploy button.

**Comment by xbotao** [comment]
Accoding to this issue([Using nodejs's spawn causes “unknown option — ” and “[Error: spawn ENOENT]” errors](https://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err?answertab=votes#tab-top))
I change 
`  //var proc = spawn(command, [message], {detached: true});`
to
`var proc = spawn((process.platform === "win32" ? "hexo.cmd" : "hexo"), ['d']);`

It works!  Thanks for your patiently reply.

**Comment by xbotao** [comment]
sorry,
just `spawn((process.platform === "win32" ? "hexo.cmd" : "hexo"), ['d']);` is not correctly.

need generate before `hexo d`
```
  var generate = spawn((process.platform === "win32" ? "hexo.cmd" : "hexo"), ['g']);
  var proc = spawn((process.platform === "win32" ? "hexo.cmd" : "hexo"), ['d']);
```

**Comment by xbotao** [comment]
what I alter.And I test it on win10 and ubuntu.
[api.js](https://github.com/xbotao/hexo-admin/blob/master/api.js#L295)
[deploy.js#13](https://github.com/xbotao/hexo-admin/blob/master/deploy.js#13)
 [deploy.js#13](https://github.com/xbotao/hexo-admin/blob/master/deploy.js#16)

**Comment by xbotao** [comment]
Could you test this code and pull it? @PirtleShell

**Comment by PirtleShell** [comment]
This is good to know, but the idea of `deployCommand` is that many things can be run on deployment, not just `hexo d -g`. I think limiting deployment to just this one command would be a regression. Did you try setting `hexo.cmd d -g` as your `deployCommand` in `_config.yml`?

The batch file also worked for you, so I think the current functionality is good. This is a great thread for someone who has problems with deploying on windows in the future though! Thanks for the thorough explanation!

**Comment by xbotao** [comment]
Got it.I think you mean，the current functionality cloud run any command you want rather than hexo g.

**Comment by PirtleShell** [comment]
That's right :smile:

**Comment by xbotao** [comment]
Accoding to the `exec` function define
```
 if (process.platform === 'win32') {
file = 'cmd.exe';
args = ['/s', '/c', '"' + command + '"'];
// Make a shallow copy before patching so we don't clobber the user's
// options object.
options = util._extend({}, options);
options.windowsVerbatimArguments = true;
} else {
  file = '/bin/sh';
  args = ['-c', command];
}
```

I think this can do like this on windows:
create a `.bat` file, content is
```
hexo deploy
```
and the deploy.js code is
```
  var proc;
  if(process.platform === "win32"){
    proc =  exec('hexo-deploy.bat');
  }else{
    proc = spawn(command, [message], {detached: true});
  }
```
the result is:
![qq 20170105094715](https://cloud.githubusercontent.com/assets/6964173/21666325/fa73979a-d32b-11e6-8a7a-e848f2de0197.png)

---
There is a disadvantage of `exec` command, the options' `maxBuffer` is limited to **200k**.
But I think **200K** is enough in this enviroment.
